[19:08:13] [main/INFO]: Using mbed TLS based native cipher.
[19:08:13] [main/INFO]: Using zlib based native compressor.
[19:08:13] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553
[19:08:13] [main/INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[19:08:13] [main/INFO]: Epoll is working, utilising it!
[19:08:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[19:08:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[19:08:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[19:08:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[19:08:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[19:08:13] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[19:08:13] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:13] [main/INFO]: Loaded plugin LuckPerms version 5.4.108 by Luck
[19:08:13] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:13] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:13] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:13] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:13] [main/INFO]: Loaded plugin bungee-rcon version 1.0.0 by Orblazer
[19:08:13] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:13] [main/INFO]: Loaded plugin Core version 1.0 by Iban_
[19:08:13] [main/WARN]: Forced host server pvp is not defined
[19:08:13] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:14] [main/INFO]:         __    
[19:08:14] [main/INFO]:   |    |__)   LuckPerms v5.4.108
[19:08:14] [main/INFO]:   |___ |      Running on BungeeCord - Waterfall
[19:08:14] [main/INFO]: 
[19:08:14] [main/INFO] [LuckPerms]: Loading configuration...
[19:08:14] [main/INFO] [LuckPerms]: Loading storage provider... [H2]
[19:08:15] [main/INFO] [LuckPerms]: Loading internal permission managers...
[19:08:15] [main/INFO] [LuckPerms]: Performing initial data load...
[19:08:15] [main/INFO] [LuckPerms]: Successfully enabled. (took 1440ms)
[19:08:15] [main/INFO]: Enabled plugin LuckPerms version 5.4.108 by Luck
[19:08:15] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:15] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:15] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:15] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:15] [main/INFO]: Binding rcon to address: 0.0.0.0/0.0.0.0:25575...
[19:08:15] [main/INFO]: Enabled plugin bungee-rcon version 1.0.0 by Orblazer
[19:08:15] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.20-R0.2-SNAPSHOT:af78b36:553 by WaterfallMC
[19:08:15] [main/INFO]: Tentative de connexion à la bdd jdbc:mysql://mariadb:3306/minecraft
[19:08:15] [main/INFO] [fr.iban.libs.com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[19:08:16] [main/INFO] [fr.iban.libs.com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@61d60e38
[19:08:16] [main/INFO] [fr.iban.libs.com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[19:08:16] [main/INFO]: Connection effectuée.
[19:08:16] [main/WARN]: Exception encountered when loading plugin: Core
java.lang.NoClassDefFoundError: me/neznamy/tab/api/TabAPI
	at fr.iban.bungeecore.utils.TabHook.enable(TabHook.java:20) ~[?:?]
	at fr.iban.bungeecore.CoreBungeePlugin.onEnable(CoreBungeePlugin.java:100) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
Caused by: java.lang.ClassNotFoundException: me.neznamy.tab.api.TabAPI
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 6 more
[19:08:16] [Netty Boss IO Thread #0/INFO]: Listening on /0.0.0.0:25566
[19:08:58] [Netty Worker IO Thread #0/INFO]: [/192.168.80.1:42134] <-> InitialHandler has pinged
[19:09:00] [Netty Worker IO Thread #1/INFO]: [/192.168.80.1:42142] <-> InitialHandler has pinged
[19:09:01] [Netty Worker IO Thread #2/INFO]: [/192.168.80.1:37834] <-> InitialHandler has connected
[19:09:02] [Netty Worker IO Thread #2/INFO]: [Iban_|/192.168.80.1:37834] <-> ServerConnector [survie] has connected
[19:09:02] [Core Pool Thread #1/INFO]: ≫ Iban_ s'est connecté pour la première fois !
[19:11:33] [Netty Worker IO Thread #2/INFO]: [Iban_] disconnected with: Server closed
[19:11:33] [Netty Worker IO Thread #2/INFO]: [/192.168.80.1:37834|Iban_] -> UpstreamBridge has disconnected
[19:11:33] [Netty Worker IO Thread #2/INFO]: [/192.168.80.1:37834|Iban_] <-> DownstreamBridge <-> [survie] has disconnected
[19:11:33] [Core Pool Thread #2/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@997d532, id=25, owner=fr.iban.bungeecore.CoreBungeePlugin@3b57dba4, task=fr.iban.bungeecore.listeners.ProxyJoinQuitListener$$Lambda$1169/0x000000080132b000@20d492c2, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
	at net.md_5.bungee.netty.ChannelWrapper.getEncodeProtocol(ChannelWrapper.java:51) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at net.md_5.bungee.UserConnection.sendPacketQueued(UserConnection.java:195) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:562) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:511) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:499) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at fr.iban.bungeecore.listeners.ProxyJoinQuitListener.lambda$onDisconnect$3(ProxyJoinQuitListener.java:158) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at fr.iban.bungeecore.listeners.ProxyJoinQuitListener.lambda$onDisconnect$4(ProxyJoinQuitListener.java:155) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[19:43:51] [Thread-11/INFO]: Closing listener [id: 0x9af6ffcd, L:/0.0.0.0:25566]
[19:43:51] [pool-5-thread-1/WARN] [fr.iban.libs.com.zaxxer.hikari.pool.ProxyConnection]: HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@633ba68f marked as broken because of SQLSTATE(08S01), ErrorCode(1053)
java.sql.SQLNonTransientConnectionException: Server shutdown in progress
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[19:43:51] [pool-5-thread-1/ERROR]: java.sql.SQLNonTransientConnectionException: Server shutdown in progress
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:43:51] [pool-5-thread-1/WARN] [fr.iban.libs.com.zaxxer.hikari.pool.ProxyConnection]: HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@67506d76 marked as broken because of SQLSTATE(08S01), ErrorCode(0)
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 2 milliseconds ago. The last packet sent successfully to the server was 2 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 2 milliseconds ago. The last packet sent successfully to the server was 2 milliseconds ago.
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	... 10 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	... 10 more
[19:43:51] [pool-5-thread-1/ERROR]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[19:43:51] [pool-5-thread-1/ERROR]: 
[19:43:51] [pool-5-thread-1/ERROR]: The last packet successfully received from the server was 2 milliseconds ago. The last packet sent successfully to the server was 2 milliseconds ago.
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:43:51] [pool-5-thread-1/ERROR]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[19:43:51] [pool-5-thread-1/ERROR]: 
[19:43:51] [pool-5-thread-1/ERROR]: The last packet successfully received from the server was 2 milliseconds ago. The last packet sent successfully to the server was 2 milliseconds ago.
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
[19:43:51] [pool-5-thread-1/ERROR]: 	... 10 more
[19:43:51] [pool-5-thread-1/ERROR]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576)
[19:43:51] [pool-5-thread-1/ERROR]: 	... 15 more
[19:43:51] [pool-5-thread-1/WARN] [fr.iban.libs.com.zaxxer.hikari.pool.ProxyConnection]: HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@2c3ff102 marked as broken because of SQLSTATE(08S01), ErrorCode(0)
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 2 milliseconds ago. The last packet sent successfully to the server was 2 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 2 milliseconds ago. The last packet sent successfully to the server was 2 milliseconds ago.
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	... 10 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	... 10 more
[19:43:51] [pool-5-thread-1/ERROR]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[19:43:51] [pool-5-thread-1/ERROR]: 
[19:43:51] [pool-5-thread-1/ERROR]: The last packet successfully received from the server was 2 milliseconds ago. The last packet sent successfully to the server was 2 milliseconds ago.
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:43:51] [pool-5-thread-1/ERROR]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[19:43:51] [pool-5-thread-1/ERROR]: 
[19:43:51] [pool-5-thread-1/ERROR]: The last packet successfully received from the server was 2 milliseconds ago. The last packet sent successfully to the server was 2 milliseconds ago.
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
[19:43:51] [pool-5-thread-1/ERROR]: 	... 10 more
[19:43:51] [pool-5-thread-1/ERROR]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576)
[19:43:51] [pool-5-thread-1/ERROR]: 	... 15 more
[19:43:51] [pool-5-thread-1/WARN] [fr.iban.libs.com.zaxxer.hikari.pool.ProxyConnection]: HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@4833ca93 marked as broken because of SQLSTATE(08S01), ErrorCode(0)
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 1 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	... 10 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	... 10 more
[19:43:51] [pool-5-thread-1/ERROR]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[19:43:51] [pool-5-thread-1/ERROR]: 
[19:43:51] [pool-5-thread-1/ERROR]: The last packet successfully received from the server was 1 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:43:51] [pool-5-thread-1/ERROR]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[19:43:51] [pool-5-thread-1/ERROR]: 
[19:43:51] [pool-5-thread-1/ERROR]: The last packet successfully received from the server was 1 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
[19:43:51] [pool-5-thread-1/ERROR]: 	... 10 more
[19:43:51] [pool-5-thread-1/ERROR]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576)
[19:43:51] [pool-5-thread-1/ERROR]: 	... 15 more
[19:43:51] [pool-5-thread-1/WARN] [fr.iban.libs.com.zaxxer.hikari.pool.ProxyConnection]: HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@6e7d7825 marked as broken because of SQLSTATE(08S01), ErrorCode(0)
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 1 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	... 10 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[waterfall-1.20-553.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:af78b36:553]
	... 10 more
[19:43:51] [pool-5-thread-1/ERROR]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[19:43:51] [pool-5-thread-1/ERROR]: 
[19:43:51] [pool-5-thread-1/ERROR]: The last packet successfully received from the server was 1 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[19:43:51] [pool-5-thread-1/ERROR]: 	at fr.iban.common.messaging.SqlMessenger.readNewMessages(SqlMessenger.java:92)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:43:51] [pool-5-thread-1/ERROR]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[19:43:51] [pool-5-thread-1/ERROR]: 
[19:43:51] [pool-5-thread-1/ERROR]: The last packet successfully received from the server was 1 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[19:43:51] [pool-5-thread-1/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1052)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:657)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
[19:43:51] [pool-5-thread-1/ERROR]: 	... 10 more
[19:43:51] [pool-5-thread-1/ERROR]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
[19:43:51] [pool-5-thread-1/ERROR]: 	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576)
[19:43:51] [pool-5-thread-1/ERROR]: 	... 15 more
